### ISSUE TITLE
Frontend TODOs

### ISSUE THREAD

**Issue by DatDraggy** [DatDraggy/summerbo.at#29]
- [x] Text below countdown is white on white
- [x] Radio Buttons
- [x] ~~DoB Picker~~
- [x] Volunteer tile in team overview is white on light grey
- [x] Waitinglist
- [x] Gallery
- [x] Image format
- [x] ~~Progress Bar~~
- [x] Assets for new name

**Comment by Oekeokiki** [comment]
Index > Team > Volunteer is white on light grey

**Comment by DatDraggy** [comment]
We should think about converting images into a different format once everything is done because our site already is veery big
According to pagespeed insights we could save up to 10s when we optimize our pics.

**Comment by Oekeokiki** [comment]
H4 headlines color need to be changed to primarycolor

**Comment by DatDraggy** [comment]
> H4 headlines color need to be changed to primarycolor


@haushaushaus _ instead of ) on purpose or not?
index.html#278

**Comment by DatDraggy** [comment]
fixed
